export {default as Checkout} from "./Checkout";
export {default as Earphones} from "./Earphones";
export {default as Headphones} from "./Headphones";
export {default as HomeLayout} from "./HomeLayout";
export {default as Landing} from "./Landing";
export {default as Login} from "./Login";
export {default as Register} from "./Register";
export {default as Singleproduct} from "./SingleProduct";
export {default as Speakers} from "./Speakers";
export {default as Error} from "./Error"
